pur_beurre_project/accounts/urls.py
'''
This file contains the urls used in the accounts app.
It allows the users to signup and manage their accounts.
'''

from django.conf.urls import url
from django.contrib.auth.views import LoginView
from django.urls import path

from accounts import views


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('dashboard/', views.dashboard, name='dashboard')
]

pur_beurre_project/pur_beurre_project/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import path, re_path

from substituter import views

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path('sentry-debug/', trigger_error),
    re_path(r'^$', views.index, name="index"), 
    path(
        r'substituter/', 
        include(('substituter.urls', 'substituter'), namespace="substituter")
    ),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace="accounts")), 
    path('bookmarks/', include(('bookmarks.urls', 'bookmarks'), namespace="bookmarks")), 
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        re_path(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

pur_beurre_project/substituter/urls.py
'''
This file contains the urls of the substituter, which is the core app of this
project. It covers product research and details, and the legal mentions page.
'''

from django.conf.urls import url
from django.urls import path

from substituter import views

urlpatterns = [
    path(r'search/', views.search, name="search"),
    path(r'detail/<int:product_id>/', views.detail, name="detail"),
    path(r'autocomplete/', views._autocomplete, name="autocomplete"),
    path(r'legal/', views.legal, name="legal")
    ]

pur_beurre_project/substituter/models.py
'''
This file contains the models for the products and their categories.
'''


from django.db import models

class Category(models.Model):
    #Category model is simply a name
    name = models.CharField(max_length=50)

class Product(models.Model):
    '''
    The product model requires a name, nutrition grade, link to OFF,
    description and image to work. Six optional fields contain the nutritional
    informations about the product.
    Finally, each product is linked to at least one category.
    '''
    barcode = models.BigIntegerField(unique=True, null=True)
    name = models.CharField(max_length=100)
    grade = models.CharField(max_length=1)
    link = models.URLField(max_length=255)
    description = models.CharField(max_length=255)
    image = models.URLField(max_length=255)
    salt = models.FloatField(null=True)
    carbohydrates = models.FloatField(null=True)
    sugars = models.FloatField(null=True)
    fats = models.FloatField(null=True)
    proteins = models.FloatField(null=True)
    fibers = models.FloatField(null=True)
    categories = models.ManyToManyField(Category)

pur_beurre_project/substituter/views.py
'''
The views of the substituter app handles core features (such as index page)
as well as the research feature, and the detailed page of a given
food product.
'''

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.sessions.models import Session
from django.http import JsonResponse

from sentry_sdk import capture_message

from .models import Product, Category

def index(request):
    #Displays home page
    return render(request, 'substituter/index.html')


def search(request):
    '''
    Searchs the database for the product with the most words in its title that
    match user's research. Then selects six other products with the most
    categories matching that of the base product, excluding those with worse
    food grades, and returns those six products as suggested substitutes.
    '''

    def _get_matching_product(input, criterion):
        '''
        This function reads each separate word in an input, and for each one 
        of them, creates a list of products with a given criterion matching
        said words. A given product can appear more than once.
        The function then returns a list of all the products found, sorted
        from most correlated to least correlated.
        '''

        results = []

        for word in input:
            if criterion == "name":
                matching_products = Product.objects.filter(name__icontains=word)
            elif criterion == "category":
                matching_products = Product.objects.filter(categories__name__icontains=word)
            for product in matching_products:
                results.append(product.pk)

        counted_results = []
        results.sort(reverse=True)
        x = 0
        while x < len (results):
            key = results[x]
            counted_results.append((key, results.count(key)))
            x += results.count(key)

        results_list = []

        for key in sorted(counted_results, 
                          key=lambda tuple: tuple[1], 
                          reverse = True):
            results_list.append(Product.objects.get(pk=key[0]))

        return results_list
        
    user_input = request.GET.get("query").split("+")

    try:
        base_product = _get_matching_product(user_input, "name")[0]

    except IndexError:
        context = {"status" : "error"}
        return render(request, 'substituter/search.html', context)

    category_list = [category.name 
                    for category 
                    in base_product.categories.all()]

    substitute_candidates = _get_matching_product(category_list, "category") 

    substitute_list = []

    for substitute in substitute_candidates:
        if substitute.grade < base_product.grade:
            substitute_list.append(substitute)

    if request.user.is_authenticated:
        context = {
        "status" : "ok connect",
        "base_product": base_product,
        "substitute_list": substitute_list[:6],
        "bookmarked_list": request.user.bookmarks.all()
        }

    else:
        context = {
        "status" : "ok",
        "base_product": base_product,
        "substitute_list": substitute_list[:6],
        "bookmarked_list": []
        }

    capture_message('New search : ' + request.GET.get("query"))

    return render(request, 'substituter/search.html', context)


def _autocomplete(request):
    string = request.GET.get('term')
    matching_products = Product.objects.filter(name__icontains=string)[:20]
    response = [product.name for product in matching_products]
    return JsonResponse(response, safe=False)


def detail(request, product_id):
    #Displays detailed information about a given product using its pk
    product = get_object_or_404(Product, pk=product_id)
    context = {
    "product": product
    }
    return render(request, 'substituter/detail.html', context)


def legal(request):
    #Displays the legal mentions page
    return render(request, 'substituter/legal.html')

pur_beurre_project/substituter/templates/substituter/base.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Pur-Beurre</title>

  {% load static %}

  <link href="{% static 'substituter/img/favicon.png' %}" rel="icon" type="image/png">

  <!-- Font Awesome Icons -->
  <link href="{% static 'substituter/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet">
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic' rel='stylesheet' type='text/css'>

  <!-- Plugin CSS -->
  <link href="{% static 'substituter/vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

  <!-- Theme CSS - Includes Bootstrap -->
  <link href="{% static 'substituter/css/creative.min.css' %}" rel="stylesheet">
  <link href="{% static 'substituter/css/custom_creative.css' %}" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css" />

</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top py-3" id="mainNav">
    <div class="container">
      <img src="{% static 'substituter/img/logo_pb.png' %}">
      <a class="navbar-brand js-scroll-trigger" href="/">Pur Beurre</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto my-2 my-lg-0">
          <li class="nav-item">
            <form class="form-inline nav-form" action="{% url 'substituter:search' %}" method="get">
              <div class="form-group">
                <input class="searchform" type="text" name="query" value="" id="name">
              </div>

              <button type="submit" class="btn btn-primary">Chercher</button>
            </form>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'accounts:dashboard' %}"><i class="fas fa-user"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'bookmarks:bookmarked' %}"><img src="{% static 'substituter/img/carrot_icon.png' %}"></a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt" alt="Déconnexion"></i></a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'login' %}"><i class="fas fa-sign-in-alt" alt="Connexion"></i></a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="{% url 'accounts:signup' %}">Inscription</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  {% block content %}{% endblock %}

  <!-- Footer -->
  <footer class="bg-light py-5">
    <div class="container">
      <div class ="row">
        <a class="col-lg-6 col-sm-6 text-center text-white" href="{% url 'substituter:legal' %}">Mentions légales</a>
        <a class="col-lg-6 col-sm-6 text-center text-white" href="/#contact">Contact</a>
      </div>
    </div>
  </footer>

  <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
  <!-- Bootstrap core JavaScript -->

  <script src="{% static 'substituter/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'substituter/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'substituter/vendor/jquery-easing/jquery.easing.min.js' %}"></script>
  <script src="{% static 'substituter/vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'substituter/js/creative.min.js' %}"></script>
  <script
  src="https://code.jquery.com/ui/1.12.0/jquery-ui.min.js"
  integrity="sha256-eGE6blurk5sHj+rmkfsGYeKyZx3M4bG+ZlFyA7Kns7E="
  crossorigin="anonymous"></script>
  <script src="{% static 'substituter/js/custom_creative.js' %}"></script>

</body>

</html>

pur_beurre_project/substituter/templates/substituter/detail.html
{% extends 'substituter/base.html' %}

{% block content %}

<!-- About Section -->
  <section class="page-section bg-primary" id="search">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-12 text-center">
          <h1> {{ product.name }} </h1>
          <img class="img-responsive" src="{{ product.image }}" alt="{{ product.name }}">
        </div>
      </div>
    </div>
  </section>

  <!-- Services Section -->
  <section class="page-section" id="about">
    <div class="container">
      <hr class="divider my-4">
      <div class="row">
        <div class="col-lg-6 col-md-6 text-center">
          <h5> Nutriscore : {{ product.grade }} </h5>
        </div>
        <div class="col-lg-6 col-md-6 text-center">
          <h5> Repères nutritionnels pour 100g </h5>
          <ul class="col-lg-6 col-md-6 text-center">
            <li>Sel : {% if product.salt %} {{ product.salt }} g {% else %} Non renseigné {% endif %} </li>
            <li>Protéines : {% if product.proteins %} {{ product.proteins }} g {% else %} Non renseigné {% endif %} </li>
            <li>Glucides : {% if product.carbohydrates %} {{ product.carbohydrates }} g {% else %} Non renseigné {% endif %} </li>
            <li>Sucres : {% if product.sugars %} {{ product.sugars }} g {% else %} Non renseigné {% endif %} </li>
            <li>Lipides : {% if product.fats %} {{ product.fats }} g {% else %} Non renseigné {% endif %} </li>
            <li>Fibres : {% if product.fibers %} {{ product.fibers }} g {% else %} Non renseigné {% endif %} </li>
          </ul>
        </div>
      </div>
      <div class="col-lg-12 col-md-12 text-center">
        <a href="{{ product.link }}"> Voir la fiche d'OpenFoodFacts</a>
      </div>
    </div>
  </section>

  

  

{% endblock %}

pur_beurre_project/substituter/templates/substituter/index.html
{% extends 'substituter/base.html' %}

{% block content %}

<header class="masthead">
  <div class="container h-100">
    <div class="row h-100 align-items-center justify-content-center text-center">
      <div class="col-lg-10 align-self-end">
        <h1 class="text-uppercase text-white font-weight-bold">Du gras, oui, mais de qualité !</h1>
        <hr class="divider my-4">
      </div>
      <div class="col-lg-8 text-center align-self-baseline">
        <h2 class="text-white mt-0">Trouvez un produit de substitution pour ceux que vous consommez tous les jours.</h2>
        <form action="{% url 'substituter:search' %}" method="get">
          <div class="form-group">
            <input class="searchform" type="text" name="query" value="" id="name">
          </div>
          <button type="submit" class="btn btn-primary">Chercher</button>
        </form>
      </div>
    </div>
  </div>
</header>

  <!-- Services Section -->
  <section class="page-section" id="about">
    <div class="container">
      <h2 class="text-center mt-0">Colette & Rémy</h2>
      <hr class="divider my-4">
      <div class="row">
        <div class="col-lg-6 col-md-12 text-center history-container">    
          <div class="bottomdiv">
            <img src="../../static/substituter/img/colette.png" alt="Portrait de Colette">
            <h3 class="h4 mb-2">Colette</h3>
            <p class="text-muted mb-0">"Nous aimons tous manger, surtout en France ! Personnellement, une baguette fraîche, du bon fromage de chèvre et un bon vin rouge me suffisent amplement. Comme tout le monde, je fais mes courses au supermarché. Mais petit à petit je me suis rendue compte, surtout lorsque nous avons ouvert le restaurant, que je pouvais remplacer les produits aseptisés que j'avais l'habitude d'acheter par de bons produits du terroir. Et souvent pour le même prix !"</p>
          </div>
        </div>
        <div class="col-lg-6 col-md-12 text-center history-container">
          <div class="bottomdiv">
            <img src="../../static/substituter/img/ratatouille.jpg" alt="Portrait de Rémy">
            <h3 class="h4 mb-2">Rémy</h3>
            <p class="text-muted mb-0">"Pour ma part je me rendais déjà dans bien des magasins car j'aime beaucoup me balader, surtout dans les caves et les cuisines. Je connaissais par coeur le contenu des boutiques bio (dont je raffole) ainsi que les ingrédients de tous les aliments vendus. Lorsque Colette m'a demandé si elle pouvait remplacer son Nutella matinal par un aliment plus sain, je savais tout de suite où le trouver. L'idée de Pur Beurre était née !"</p>
          </div>
        </div>
      </div>
    </div>
  </section>


  <!-- Contact Section -->
  <section class="page-section bg-primary" id="contact">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8 text-center">
          <h2 class="mt-0 text-white">Contactez-nous !</h2>
          <hr class="divider my-4">
          <p class="text-white mb-5">Du gras, oui, mais de qualité !</p>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
          <i class="fas fa-phone fa-3x mb-3 text-white"></i>
          <h6 class="text-white">0000000000</h6>
        </div>
        <div class="col-lg-4 mr-auto text-center">
          <i class="fas fa-envelope fa-3x mb-3 text-white"></i>
          <h6 class="text-white">mail@mail.com</h6>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

pur_beurre_project/substituter/templates/substituter/legal.html
{% extends 'substituter/base.html' %}

{% block content %}


  <section class="page-section bg-img" >
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-12 text-center">
          <h1 class="mb-2 text-uppercase text-white font-weight-bold"> Mentions légales </h1>
        </div>
      </div>
    </div>
  </section>

  <section class="page-section" >
    <div class="container">
        <div class="col-lg-12 col-md-12 text-left">
          <h5>Notre hébergeur : <a href="https://www.heroku.com/">Heroku</a></h5>
          <h5>Notre thème : <a href="https://blackrockdigital.github.io/startbootstrap-creative/">Creative</a>, de <a href="https://startbootstrap.com/">Start Boostrap</a></h5>
          <h5>Photo de la page d'accueil : <a href="https://unsplash.com/@gregjeanneau">Greg Jeanneau sur Unsplash</a></h5>
          <h5>Icône de carotte : Fabien Jouin de <a href="https://thenounproject.com">Noun Project</a></h5>
          <h5>Autres icônes : <a href="https://icomoon.io">IconMoon</a> et <a href="https://fontawesome.com/">Font Awesome</a></h5>
          <h5>Images : <a href="https://fr.wikipedia.org/wiki/Ratatouille_(film)">Ratatouille (film d'animation de Disney-Pixar, 2007)</a></h5>
        </div>
    </div>
  </section>

  



{% endblock %}

pur_beurre_project/substituter/templates/substituter/search.html
{% extends 'substituter/base.html' %}

{% block content %}

<!-- About Section -->
  <section class="page-section bg-img" id="search">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-12 text-center">
          {% if status == "ok" %}
          <img class="img-responsive" src="{{ base_product.image }}" alt="{{ base_product.name }}">
          {% endif %}
        </div>
      </div>
    </div>
  </section>

  <!-- Services Section -->
  <section class="page-section" id="about">
    <div class="container">
      {% if substitute_list %}
      <h2 class="text-center mt-0">Vous pouvez remplacer cet aliment par :</h2>
      <div class="row">
        {% for substitute in substitute_list %}
          <div class="col-lg-4 col-md-12 text-center product">
            <p class="nutriscore">{{ substitute.grade }}</p>
            <a class="product-picture" href="{% url 'substituter:detail' product_id=substitute.id %}">
              <img class="img-responsive product-pic" src="{{ substitute.image }}" alt="{{ substitute.name }}">
              <h4 class="h4 mb-2">{{ substitute.name }}</h4>
            </a>
            {% if substitute not in bookmarked_list %}
            <a class="h4 mb-2 text-muted mb-0" href="{% url 'bookmarks:save' substitute_id=substitute.id %}"><i class="fas fa-save"> </i>Sauvegarder</a>
            {% else %}
            <p class="h4 mb-2 text-muted mb-0">Sauvegardé !</p>
            {% endif %}
          </div>
        {% endfor %}
      </div>
      {% elif status == "ok" %} 
      <h2 class="text-center mt-0">Aucun aliment plus sain n'a été trouvé</h2>
      {% else %}
      <h2 class="text-center mt-0">Aucun aliment ne correspond à votre recherche</h2>
      {% endif %}
    </div>
  </section>

  

  

{% endblock %}